#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "machaudio/arena.h"
#include "machaudio/vad_gru.h"
#include "unity.h"

// Forward declarations of inner processing functions for exact comparison testing
extern float vad_gru_process_frame_c(
    VadGruState *const state,
    float const *const restrict features,
    size_t const num_features);

#ifdef __AVX2__
extern float vad_gru_process_frame_avx2(
    VadGruState *const state,
    float const *const restrict features,
    size_t const num_features);
#endif

// Include the autogenerated training data for functional validation
#include "../../src/processing/vad_training_loader.h"
#include "machaudio/macros.h"

void test_vad_gru_alignment_and_alloc(void) {
    Arena arena;
    // Align base buffer to 32 bytes for AVX
    alignas(32) uint8_t raw_buf[1024];

    arena_init(&arena, raw_buf, sizeof(raw_buf), "vad");

    // Allocate a random chunk first to fragment alignment
    void *dummy = arena_alloc(&arena, 13);
    TEST_ASSERT_NOT_NULL(dummy);

    // Initialize the VAD state
    VadGruState *state = vad_gru_init(&arena);
    TEST_ASSERT_NOT_NULL(state);

    // Verify 32-byte boundary alignment
    uintptr_t addr = (uintptr_t)state;
    TEST_ASSERT_EQUAL(0, addr % 32);

    // Verify reset zeros out state
    for (size_t i = 0; i < VAD_HIDDEN_DIM; ++i) {
        TEST_ASSERT_EQUAL_FLOAT(0.0f, state->hidden_state[i]);
    }
}

void test_vad_gru_reset(void) {
    Arena   arena;
    uint8_t buf[1024];
    arena_init(&arena, buf, sizeof(buf), "vad");

    VadGruState *state = vad_gru_init(&arena);
    TEST_ASSERT_NOT_NULL(state);

    // Manually pollute hidden state
    for (size_t i = 0; i < VAD_HIDDEN_DIM; ++i) {
        state->hidden_state[i] = 123.45f;
    }

    vad_gru_reset(state);

    for (size_t i = 0; i < VAD_HIDDEN_DIM; ++i) {
        TEST_ASSERT_EQUAL_FLOAT(0.0f, state->hidden_state[i]);
    }
}

void test_vad_gru_c_vs_avx2_bit_exactness(void) {
#ifndef __AVX2__
    TEST_IGNORE_MESSAGE(
        "AVX2 is not supported on this compiler target; skipping bit-exactness check.");
#else
    Arena   arena;
    uint8_t buf[2048];
    arena_init(&arena, buf, sizeof(buf), "vad");

    VadGruState *state_c   = vad_gru_init(&arena);
    VadGruState *state_avx = vad_gru_init(&arena);
    TEST_ASSERT_NOT_NULL(state_c);
    TEST_ASSERT_NOT_NULL(state_avx);

    char const     *filepath = mach_getenv("MACH_VAD_DATA");
    VadTrainingData data     = vad_training_data_load(filepath);

    // Test exact math logic over all validation frames
    for (size_t f = 0; f < data.num_frames; ++f) {
        float const *features = &data.features[f * VAD_FEATURE_DIM];

        // Assert initial hidden states matching within epsilon (since fast approximations
        // accumulate)
        for (size_t i = 0; i < VAD_HIDDEN_DIM; ++i) {
            TEST_ASSERT_FLOAT_WITHIN(1e-4f, state_c->hidden_state[i], state_avx->hidden_state[i]);
        }

        // Execute both implementations
        float prob_c   = vad_gru_process_frame_c(state_c, features, VAD_FEATURE_DIM);
        float prob_avx = vad_gru_process_frame_avx2(state_avx, features, VAD_FEATURE_DIM);

        // Verify output probability matches within tiny epsilon
        TEST_ASSERT_FLOAT_WITHIN(1e-4f, prob_c, prob_avx);

        // Verify resulting hidden states match within tiny epsilon
        for (size_t i = 0; i < VAD_HIDDEN_DIM; ++i) {
            TEST_ASSERT_FLOAT_WITHIN(1e-4f, state_c->hidden_state[i], state_avx->hidden_state[i]);
        }
    }

    vad_training_data_free(&data);
#endif
}

void test_vad_gru_functional_accuracy(void) {
    Arena   arena;
    uint8_t buf[1024];
    arena_init(&arena, buf, sizeof(buf), "vad");

    VadGruState *state = vad_gru_init(&arena);
    TEST_ASSERT_NOT_NULL(state);

    char const     *filepath = mach_getenv("MACH_VAD_DATA");
    VadTrainingData data     = vad_training_data_load(filepath);

    size_t correct_predictions = 0;

    printf("\n--- VAD Functional Validation ---\n");
    // Iterate over all training / validation frames
    for (size_t f = 0; f < data.num_frames; ++f) {
        float const *features = &data.features[f * VAD_FEATURE_DIM];
        float        target   = data.labels[f];

        float prob = vad_gru_process_frame(state, features, VAD_FEATURE_DIM);

        // Quantize prediction using a 0.5 threshold
        float prediction = (prob >= 0.5f) ? 1.0f : 0.0f;
        if (prediction == target) {
            correct_predictions++;
        }

        if (f >= 90 && f <= 130) {
            printf(
                "Frame %3zu | Target: %.1f | Prob: %.6f | Prediction: %.1f | %s\n",
                f,
                target,
                prob,
                prediction,
                (prediction == target) ? "OK" : "FAIL");
        }
    }

    float accuracy = (float)correct_predictions / data.num_frames;
    printf("Total Accuracy: %.2f%%\n", accuracy * 100.0f);

    vad_training_data_free(&data);

    // Assert functional VAD accuracy is high on training set (> 70% to account for transition
    // hangover)
    TEST_ASSERT_TRUE(accuracy > 0.70f);
}

void test_vad_gru_process_pcm_silence(void) {
    Arena   arena;
    uint8_t buf[1024];
    arena_init(&arena, buf, sizeof(buf), "vad");

    VadGruState *state = vad_gru_init(&arena);
    TEST_ASSERT_NOT_NULL(state);

    // Silence frame: 320 samples of 0
    int16_t pcm[320] = {0};
    float   prob     = vad_gru_process_pcm(state, pcm, 320, 16000, 1);
    TEST_ASSERT_TRUE(prob < 0.3f);
}

void test_vad_gru_process_pcm_sine(void) {
    Arena   arena;
    uint8_t buf[1024];
    arena_init(&arena, buf, sizeof(buf), "vad");

    VadGruState *state = vad_gru_init(&arena);
    TEST_ASSERT_NOT_NULL(state);

    // Loud sine frame: 320 samples at 1000Hz (highly active)
    int16_t pcm[320];
    for (int i = 0; i < 320; ++i) {
        pcm[i] = (int16_t)(30000.0f * sinf(2.0f * M_PI * 1000.0f * i / 16000.0f));
    }

    float prob = vad_gru_process_pcm(state, pcm, 320, 16000, 1);
    TEST_ASSERT_TRUE(prob > 0.7f);
}
